<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\money\\amount' => '/Amount.php',
                'spriebsch\\money\\currency' => '/Currency.php',
                'spriebsch\\money\\fraction' => '/Fraction.php',
                'spriebsch\\money\\money' => '/Money.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
